def add(text, name):

    #text += "E5(" + name + ")\n"
    text += name + "\n"
    text += "Level: 86\n"
    text += "EVs: 252 HP / 252 Atk / 252 Def / 252 SpA / 252 SpD / 252 Spe\n"
    return text


text = ""
text = add(text, 'Ribombee')
text = add(text, 'Granbull')
text = add(text, 'Crawdunt')
text = add(text, 'Dewgong')
text = add(text, 'Mothim')
text = add(text, 'Altaria')
text = add(text, 'Altaria-Mega')
text = add(text, 'Morpeko')
text = add(text, 'Venusaur')
text = add(text, 'Venusaur-Mega')
text = add(text, 'Gothitelle')
text = add(text, 'Scolipede')
text = add(text, 'Exeggutor-Alola')
text = add(text, 'Solrock')
text = add(text, 'Blaziken')
text = add(text, 'Blaziken-Mega')
text = add(text, 'Watchog')
text = add(text, 'Muk-Alola')
text = add(text, 'Komala')
text = add(text, 'Lapras')
text = add(text, 'Lapras-Mega')
text = add(text, 'Gyarados')
text = add(text, 'Gyarados-Mega')
text = add(text, 'Marowak')
text = add(text, 'Marowak-Alola')
text = add(text, 'Dugtrio')
text = add(text, 'Seaking')
text = add(text, 'Lanturn')
text = add(text, 'Machamp')
text = add(text, 'Manectric')
text = add(text, 'Slaking')
text = add(text, 'Roserade')
text = add(text, 'Greninja')
text = add(text, 'Barraskewda')
text = add(text, 'Bisharp')
text = add(text, 'Drampa')
text = add(text, 'Tentacruel')
text = add(text, 'Snorlax')
text = add(text, 'Snorlax-Mega')
text = add(text, 'Wailord')
text = add(text, 'Drifblim')
text = add(text, 'Thievul')
text = add(text, 'Torkoal')
text = add(text, 'Sceptile')
text = add(text, 'Sceptile-Mega')
text = add(text, 'Audino')
text = add(text, 'Audino-Mega')
text = add(text, 'Kingdra')
text = add(text, 'Aegislash')
text = add(text, 'Conkeldurr')
text = add(text, 'Latios')
text = add(text, 'Latios-Mega')
text = add(text, 'Swampert')
text = add(text, 'Swampert-Mega')
text = add(text, 'Politoed')
text = add(text, 'Slowbro')
text = add(text, 'Slowbro-Mega')
text = add(text, 'Skarmory')
text = add(text, 'Ferrothorn')

print(text)