from _moves import *

def LEVEL_UP_MOVE(level: int, move):
    return {level: move}

LEVEL_UP_END = None

LEVEL_UP_MOVE( 1, MOVE_TACKLE),
	LEVEL_UP_MOVE( 1, MOVE_GROWL),
	LEVEL_UP_MOVE( 3, MOVE_VINEWHIP),
	LEVEL_UP_MOVE( 6, MOVE_GROWTH),
	LEVEL_UP_MOVE( 9, MOVE_LEECHSEED),
	LEVEL_UP_MOVE(12, MOVE_RAZORLEAF),
	LEVEL_UP_MOVE(15, MOVE_POISONPOWDER),
	LEVEL_UP_MOVE(15, MOVE_SLEEPPOWDER),
	LEVEL_UP_MOVE(18, MOVE_TAKEDOWN),
	LEVEL_UP_MOVE(21, MOVE_SEEDBOMB),
	LEVEL_UP_MOVE(24, MOVE_SWEETSCENT),
	LEVEL_UP_MOVE(27, MOVE_SYNTHESIS),
	LEVEL_UP_MOVE(30, MOVE_WORRYSEED),
	LEVEL_UP_MOVE(33, MOVE_DOUBLEEDGE),
	LEVEL_UP_MOVE(36, MOVE_SOLARBEAM),
	LEVEL_UP_END
